### ISSUE TITLE
provide a version constraint for the ricbra/robots-txt-bundle requirement

### ISSUE THREAD

**Issue by sherlyfebrianti96** [ricbra/robots-txt-bundle#1] opened 2015-06-22 05:42 UTC
when i run this
composer require ricbra/robots-txt-bundle
it appears : Please provide a version constraint for the ricbra/robots-txt-bundle requirement
what should i do?

**Comment by ricbra** [comment] 2015-06-22 15:55
Hi @sherlyfebrianti96 

That's strange. Perhaps your "minimum-stability" is on a different level than "dev"?

You could try version "^1.0@dev" which I get when running <code>composer require ricbra/robots-txt-bundle</code>.

**Comment by ricbra** [comment] 2015-06-30 08:51
Closing this for now assuming the problem is solved.

**Closed as completed by ricbra** 2015-06-30 08:51 UTC
